#!/usr/bin/env bash
# Generate / refresh homebrew-queria Formula/queria-cli.rb from a live GitHub Release.
#
# Usage:
#   ./scripts/generate_homebrew_formula.sh cli-v0.1.0
#   ./scripts/generate_homebrew_formula.sh cli-v0.1.0 --out ../homebrew-queria/Formula/queria-cli.rb
#   GH_TOKEN=… ./scripts/generate_homebrew_formula.sh cli-v0.1.0   # private repo
#
# Requires: curl, shasum/sha256sum. Does not commit or push the tap.

set -euo pipefail

REPO="${QUERIA_BACKEND_REPO:-nandocoeg2/queria-backend}"
TAG="${1:-}"
OUT=""
shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="${2:-}"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$TAG" || "$TAG" != cli-v* ]]; then
  echo "usage: $0 cli-vX.Y.Z [--out path/to/queria-cli.rb]" >&2
  exit 2
fi

VERSION="${TAG#cli-}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEFAULT_OUT="$(cd "$ROOT/.." && pwd)/homebrew-queria/Formula/queria-cli.rb"
OUT="${OUT:-$DEFAULT_OUT}"

AUTH=()
if [[ -n "${GH_TOKEN:-${GITHUB_TOKEN:-${HOMEBREW_GITHUB_API_TOKEN:-}}}" ]]; then
  TOKEN="${GH_TOKEN:-${GITHUB_TOKEN:-$HOMEBREW_GITHUB_API_TOKEN}}"
  AUTH=(-H "Authorization: Bearer ${TOKEN}" -H "Accept: application/octet-stream")
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

fetch_sha() {
  local asset="$1"
  local url="https://github.com/${REPO}/releases/download/${TAG}/${asset}"
  local dest="$tmpdir/$asset"
  echo "fetch $url" >&2
  if ! curl -fsSL "${AUTH[@]}" -o "$dest" "$url"; then
    echo "FAIL: cannot download $asset (is the Release public/live? private → set GH_TOKEN)" >&2
    return 1
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$dest" | awk '{print $1}'
  else
    sha256sum "$dest" | awk '{print $1}'
  fi
}

need_assets=(
  queria-cli-aarch64-apple-darwin.tar.gz
  queria-cli-x86_64-apple-darwin.tar.gz
  queria-cli-x86_64-unknown-linux-gnu.tar.gz
)

# Optional Linux arm
optional_assets=(
  queria-cli-aarch64-unknown-linux-gnu.tar.gz
)

declare -A SHA=()
for a in "${need_assets[@]}"; do
  SHA["$a"]="$(fetch_sha "$a")"
done

LINUX_ARM_BLOCK=""
if sha_arm="$(fetch_sha "${optional_assets[0]}" 2>/dev/null)"; then
  SHA["${optional_assets[0]}"]="$sha_arm"
  LINUX_ARM_BLOCK=$(cat <<EOF
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/queria-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA[queria-cli-aarch64-unknown-linux-gnu.tar.gz]}"
    end
EOF
)
else
  echo "warn: linux arm64 asset missing; formula will only support linux intel" >&2
  LINUX_ARM_BLOCK=$(cat <<'EOF'
    on_arm do
      odie "queria-cli: no aarch64-unknown-linux-gnu asset for this release"
    end
EOF
)
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# frozen_string_literal: true

# Generated by queria-backend/scripts/generate_homebrew_formula.sh
# Release: ${TAG}  Repo: ${REPO}
# Do not hand-edit sha256; re-run the script after each CLI release.

class QueriaCli < Formula
  desc "QuerIa CLI for laptop index-here (Needs review ingest)"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/queria-cli-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA[queria-cli-aarch64-apple-darwin.tar.gz]}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/queria-cli-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA[queria-cli-x86_64-apple-darwin.tar.gz]}"
    end
  end

  on_linux do
${LINUX_ARM_BLOCK}
    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/queria-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA[queria-cli-x86_64-unknown-linux-gnu.tar.gz]}"
    end
  end

  def install
    bin.install "queria-cli"
  end

  test do
    assert_match "index-here", shell_output("#{bin}/queria-cli index-here --help")
  end
end
EOF

echo "wrote $OUT" >&2
echo "next: commit+push homebrew-queria, then: brew update && brew reinstall nandocoeg2/queria/queria-cli" >&2
